import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

def generate_visuals():
    # Ensure the output directory exists
    os.makedirs('reports/visualizations', exist_ok=True)
    
    # Load the results generated by sentiment_engine.py
    df = pd.read_csv('data/sentiment_results.csv')
    
    # 1. Pie Chart: Overall Sentiment Distribution 
    plt.figure(figsize=(8, 6))
    df['sentiment'].value_counts().plot.pie(autopct='%1.1f%%', colors=['seagreen', 'crimson', 'silver'])
    plt.title('Overall Sentiment Distribution - Gamage Recruiters')
    plt.savefig('reports/visualizations/sentiment_pie_chart.png')
    
    # 2. Bar Chart: Sentiment per Platform 
    plt.figure(figsize=(10, 6))
    sns.countplot(x='platform', hue='sentiment', data=df)
    plt.title('Sentiment by Platform')
    plt.savefig('reports/visualizations/platform_bar_chart.png')
    
    print("Step 7 Complete: Charts saved to reports/visualizations/")

if __name__ == "__main__":
    generate_visuals()